---
title: "Data Tidying"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
library(dplyr)
library(tidyr)
library(readr)
```

package::function eg dplyr::filter
install.packages("dplyr")

cmd + option + i mac
ctrl + alt + i

## Clean data

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
head(catch_original)
```
- drop All and notes since we don't need them

```{r}
catch_data <- catch_original %>% 
  # select(Region, Year, Chinook, Coho, Pink, Chum, Sockeye)
  select(-All, -notesRegCode)

summary(catch_data)
```

- change Chinook from character to numeric type

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", "1", Chinook)) %>% 
  mutate(Chinook = as.numeric(Chinook))

head(catch_clean)
```

### finding spurious characters in Chinook column

```{r}
i <- which(is.na(catch_clean$Chinook))
catch_original[i, ]
```

## reshaping data

- move from wide to long format

```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "Species", values_to = "Catch") %>% 
  rename(catch_thousands = Catch) %>% 
  mutate(catch = catch_thousands * 1000) %>% 
  select(-catch_thousands)
  

head(catch_long)
```

```{r}
catch_wide <- catch_long %>% 
  pivot_wider(names_from = Region, values_from = catch)

head(catch_wide)
```




## Split-Apply-Combine

- mean catch by region

```{r}
mean_region <- catch_long %>% 
  filter(Species == "Sockeye") %>% 
  group_by(Region, Species) %>% 
  summarise(catch_mean = mean(catch), 
            n = n(), .groups = "drop")

head(mean_region)
```


## Joins

```{r}
region_defs <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>% 
    select(code, mgmtArea) %>% 
    rename(Region = code)

head(region_defs)
```

```{r}
catch_joined <- left_join(catch_long, region_defs, by = "Region")



```

