---
title: "Data Visualisation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
```

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error = function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)

head(esc)
```

- annual escapement count (total) by species
lubridate::year()

```{r}
annual_esc <- esc %>% 
  separate(sampleDate, into = c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum"))

head(annual_esc)
```

## ggplot

barplot

```{r}
my_theme <- theme_bw() +
  theme(legend.position = "bottom")

ggplot(annual_esc, mapping = aes(x = Species, y = escapement, fill = SASAP.Region)) +
  geom_col(position = "stack") +
  my_theme
```

```{r}
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")
```

```{r}


ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) +
  geom_point() +
  scale_color_brewer(palette = "Dark2") +
  scale_y_continuous(labels = comma, n.breaks = 3) +
  geom_line() +
  ylab("Escapement (num fish)") +
  ggtitle("Kodiak Escapement") +
  my_theme

```

## leaflet

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addPopups()
```

